name: Get a @zenithhacks.org email
description: File a request to receive a Zenith Hacks official email
title: "[EMAIL]: "
labels: ["email"]
assignees:
  - leowilkin
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form. We hope you find this useful. If you run into difficulties, please contact leo@zenithhacks.org or @leowilkin (LKMW) on Slack.
  - type: input
    id: existing-contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? You **must** provide an email you are contactable on.
      placeholder: ex. leo@wilkin.xyz or @LKMW on Slack
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Your Name
      description: What's your name for the account? Full, sensible name please!
      placeholder: ex. Leo Wilkin
    validations:
      required: true
  - type: input
    id: new-email
    attributes:
      label: Your New Zenith Hacks Email
      description: Please enter the full email address you are requesting. This MUST be your full, first name. If the email you are requesting has already been taken, @leowilkin will contact you.
      placeholder: ex. leo@zenithhacks.org, NOT l@, or leow@
      value: "@zenithhacks.org"
    validations:
      required: true
  - type: input
    id: why
    attributes:
      label: Why do you need access?
      description: Please tell us why you think you need an email.
      placeholder: I need an email to email sponsors
      value: I would like a Zenith Hacks email so I can...
    validations:
      required: true
  - type: dropdown
    id: role
    attributes:
      label: What is your role with Zenith Hacks
      description: We need to find out whether you are eligible for an email address.
      options:
        - I am a core team member!
        - I am a participant!
        - I am Orpheus!
        - I have no clue why I am doing this form
        - Other (please add details above)
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our [Code of Conduct](https://github.com/zenith-hacks/code-of-conduct/blob/main/code_of_conduct.md) and the [Zenith Google Workspace Code of Conduct](https://github.com/zenith-hacks/code-of-conduct/blob/main/g-workspace-conduct.md)
      options:
        - label: I agree to follow Zenith Hack's Code of Conduct
          required: true
        - label: I agree to follow Zenith Hack's Google Workspace Code of Conduct
          required: true
